name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: '¡Felicidades! ⌣ Tu primer issue'
        pr-message: '¡Felicidades! ✓ Tu primer PR'
